### ISSUE TITLE
Need certificates for speakers

### ISSUE THREAD

**Issue by fatecabag** [mozillaph/advocacy#1]
Session 2
NPC - Commisioner - Raymund Liboro
FMA - Executive Director - Alan Alegre

**Comment by dzeysimarkez** [comment]
![certificate-fma](https://cloud.githubusercontent.com/assets/12371546/19407573/ef731f34-92d8-11e6-8e5f-dc420e13c5b6.jpg)
![certificate-npc](https://cloud.githubusercontent.com/assets/12371546/19407578/02149a28-92d9-11e6-9280-62f0c9c46e09.jpg)
