### ISSUE TITLE
Need summary for The Overview Session

### ISSUE THREAD

**Issue by fatecabag** [mozillaph/advocacy#2]
to serve as initial draft for the blogpost

Summary includes:
- [x] Number of attendees
- [x] Pictures
- [x] Topics talked about

**Comment by dzeysimarkez** [comment]
List of attendees [**here**](https://docs.google.com/a/mozillaphilippines.org/spreadsheets/d/1ZLX7XlBWLiDBT2ewp1zLK-puC2hxdosKaGeEkD0g2iA/edit?usp=sharing)

**Comment by dzeysimarkez** [comment]
**Topics talked about**
- Introduction to Mozilla Advocacy by Marquez John Christian
- Data Privacy by Billy Billones
- Software Built to Protect the Privacy of its Users - Jun Ramos

**Comment by fatecabag** [comment]
Ask for the credentials for the flickr account of mozph and palagay na lang dun :)
