### ISSUE TITLE
Event Pages for Session 3

### ISSUE THREAD

**Issue by fatecabag** [mozillaph/advocacy#3]
- [x] [Facebook](url)
- [x] [Eventbrite](http://onlineprivacyandinternetlawsblockout.eventbrite.com)

[Publicity Material](https://goo.gl/2fi4lg)

**Comment by dzeysimarkez** [comment]
![img3](https://cloud.githubusercontent.com/assets/12371546/19410396/10d0ba2a-931e-11e6-82d6-7480d7bfe6b8.jpg)

**Ticket [url]**(https://onlineprivacyandinternetlawsblockout.eventbrite.com/)

**Topics**:
- Social Engineering
- Firefox & Lightbeam
- Cookies & Third Parties
- Password

**Comment by fatecabag** [comment]
[Facebook event](https://www.facebook.com/events/1076892569093181/)
Will go live at October 18, 9AM

**Comment by fatecabag** [comment]
Please update evenbrite details to include topics. You can check on the fb details. @marquezjohnchristian
