### ISSUE TITLE
Activities for Session 3

### ISSUE THREAD

**Issue by dzeysimarkez** [mozillaph/advocacy#5]

**Comment by dzeysimarkez** [comment]
# Topics
- [x] Social Engineering
- [x] Lightbeam for Firefox
- [x] Cookies & third parties
- [x] Password

**Comment by ryanermita** [comment]
Yo guys maybe you can use some of these activity kits from learning.mozilla.org
- [Online Tracking](https://d157rqmxrxj6ey.cloudfront.net/mozstacy/21938/)
- [Privacy Basics: Passwords, Tracking, and Data Retention](https://learning.mozilla.org/en-US/activities/privacy-basics/)
- [Protect Your Data](https://learning.mozilla.org/en-US/activities/protect-your-data/)

**Comment by ryanermita** [comment]
maybe we can invite some ethical hacker to talk about social engineering. @marquezjohnchristian

**Comment by fatecabag** [comment]
Do you still need an ethical hacker? I can try  [Alexis Lingad](https://branded.me/alexis-john-lingad)

**Comment by junangelodejesus** [comment]
**Presentation for Cookies and Third Parties.**
To be updated.

[](https://docs.google.com/presentation/d/1rprl-lkR0tIWB4BD9jZXv6VR9qmb_drzfBunYp53veY/edit?usp=sharing)

**Comment by junangelodejesus** [comment]
**Presentation for Cookies and Third Parties.**
To be updated.

[Cookies](http://bit.ly/2dpX6z7)

**Comment by ryanermita** [comment]
Hi all,

We use this slide last privacy month. you can use this as additional resources and on the last part of the slide you can see more helpful links :)
[Online Privacy Awareness](https://docs.google.com/presentation/d/1iTI2X3vFeYq_-zsjv0VOmN1q7JqhHXAQ_UfMfIl63H8/edit#slide=id.gf780cecb2_3_40)

**Comment by ryanermita** [comment]
additional resources
[India Privacy wiki](https://wiki.mozilla.org/India/task_force/Policy_and_Advocacy#Resources)

**Comment by ryanermita** [comment]
@junangelodejesus Request access for online privacy awareness slide granted! :+1:

**Comment by dzeysimarkez** [comment]
@fatecabag The topic "Social Engineering" will  be handled by @ntayungao already. Maybe we can invite Alex some other time.

**Comment by junangelodejesus** [comment]
**Bingo Cards for People Bingo Game about Cookies**

[Browser Cookies](http://myfreebingocards.com/bingo-card-generator/results/zz4e9)

**Comment by junangelodejesus** [comment]
FINISHED:

**Presentation for Cookies and Third Parties:** [Click Here](https://docs.google.com/presentation/d/1rprl-lkR0tIWB4BD9jZXv6VR9qmb_drzfBunYp53veY/edit?usp=sharing)

**Bingo Cards for People Bingo:** [Get It Here](http://myfreebingocards.com/bingo-card-generator/results/zz4e9)

**Printing of Bingo Cards:** On-Going...

**Comment by ryanermita** [comment]
Great work  @junangelodejesus ! :+1:

**Comment by ntayungao** [comment]
[social engineering](https://docs.google.com/presentation/d/1vh_jUzChaf3UfzqieW6KHlG7_zBwS9S2_SMOYUC7t70/edit#slide=id.gc6f75fceb_0_65)

**Comment by ntayungao** [comment]
Finished
[Social Engineering](https://docs.google.com/presentation/d/1vh_jUzChaf3UfzqieW6KHlG7_zBwS9S2_SMOYUC7t70/edit#slide=id.gc6f75fceb_0_65)

[Lightbeam](https://docs.google.com/presentation/d/1Ty3yi447WdN0_2B0ZwsLHkN6PKjHTUfR6tLfi1lhY_Y/edit#slide=id.p)

**Comment by dzeysimarkez** [comment]
Topic: Passwords
Slides: [Slides.pptx](https://github.com/mozillaph/advocacy/files/552386/Slides.pptx)
