### ISSUE TITLE
Need summary for The Lawsuit Session

### ISSUE THREAD

**Issue by fatecabag** [mozillaph/advocacy#9]
### Description:

Summary to be used as draft for Blog post
### Related Issues & Links (if any):

Issues: #4 
### To Do
- [x] Number of attendees
- [x] Speakers and Topics
- [x] Pictures

**Comment by dzeysimarkez** [comment]
List of attendees [**here**](https://docs.google.com/a/mozillaphilippines.org/spreadsheets/d/1G5U66SA44unxxvKYhVvgeRFJDPpEf4Ie6J0kXGEEFas/edit?usp=sharing)

**Comment by dzeysimarkez** [comment]
**Speakers & Topics**
- **ICT Policies** - **Mr. Alan Alegre**, _Executive Director of Foundation for Media Alternatives_ 
- **Data Privacy Act of 2012** - **Atty. Reynaldo Flores**, _Local Division Chief of Nat'l Privacy Comission_
